name: Dev environment CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches the full Git history

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get Date for Tag
        id: get_date
        run: |
          DATE_TAG=$(date +'%d%m%Y')
          echo "DATE_TAG=$DATE_TAG" >> $GITHUB_ENV

      - name: Build Docker Image
        env:
          NEXT_PUBLIC_SERVER_API_URL: ${{ secrets.NEXT_PUBLIC_SERVER_API_URL}}
          NEXT_PUBLIC_CLIENT_API_URL: ${{ secrets.NEXT_PUBLIC_CLIENT_API_URL}}

        run: |
          docker build \
            --build-arg NEXT_PUBLIC_SERVER_API_URL=$NEXT_PUBLIC_SERVER_API_URL \
            --build-arg NEXT_PUBLIC_CLIENT_API_URL=$NEXT_PUBLIC_CLIENT_API_URL \
            -t coldbolt/jobsbolt-website:main-latest \
            -t coldbolt/jobsbolt-website:${{ env.DATE_TAG }}-main \
            .
      - name: Push Docker Image
        run: |
          docker push coldbolt/jobsbolt-website:main-latest
          docker push coldbolt/jobsbolt-website:${{ env.DATE_TAG }}-main
